# Development Environment Configuration
environment: development

database:
  host: localhost
  port: 5432
  name: ragent_chatbot_dev
  user: postgres
  password: password
  ssl_mode: prefer
  pool_size: 5
  max_overflow: 10

api:
  timeout: 30
  retry_attempts: 3
  retry_delay: 1.0
  rate_limit: 100
  rate_limit_window: 60

cache:
  enabled: true
  ttl: 300
  backend: memory
  redis_host: localhost
  redis_port: 6379
  redis_db: 0

logging:
  level: DEBUG
  file: logs/ragent_chatbot_dev.log
  structured: false
  colored: true
  max_file_size: 10485760  # 10MB
  backup_count: 5

llm:
  model_name: qwen-plus-2025-04-28
  max_tokens: 3000
  timeout: null
  max_retries: 2
  temperature: 0.7

security:
  secret_key: dev-secret-key-change-in-production
  jwt_expiry: 3600
  password_min_length: 8
  max_login_attempts: 5
  lockout_duration: 900

performance:
  enable_async: true
  max_workers: 2
  connection_pool_size: 10
  request_timeout: 30
  enable_compression: true
